### ISSUE TITLE
Donaciones Duplicadas

### ISSUE THREAD

**Issue by NicoBuch** [lbadi/AlimentAr-donante-android#2]
Cuando quise crear una donacion, estaba medio tildado y volvi a apretar y se me crearon 2 donaciones iguales. Se podrá hacer algun tipo de bloqueo al boton para que no se puedan crear varias donaciones seguidas iguales?

**Comment by NicoBuch** [comment]
@lbadi

**Comment by lbadi** [comment]
Si, falta ponerle un spinner para que veas que esta cargando y no se trabajo ademas de desactivarle el botón para que no lo pueda tocar varias veces.
