### ISSUE TITLE
Crash en Push Notifications

### ISSUE THREAD

**Issue by NicoBuch** [lbadi/AlimentAr-donante-android#3]
Creo que arreglé lo de las push notifications. Al menos no me tira ningun tipo de error desde mi lado. 
El tema es que cuando le mando una push, la app de donantes crashea. La push nunca llega.

**Comment by NicoBuch** [comment]
@lbadi

**Comment by lbadi** [comment]
Debe estar fallando por que busca ciertos campos en el mensaje que mandas vos y no los esta encontrando. Hay que ponerse de acuerdo en que campos vas a enviar vos, con que información. Ya que sea la push que sea, yo solo recibo un mensaje y a partir de ahí tengo que generar las diferentes notificaciones.
De todas maneras tengo que hacer un checkeo para que no falle.
