### ISSUE TITLE
No se está haciendo el save_token

### ISSUE THREAD

**Issue by NicoBuch** [lbadi/AlimentAr-donante-android#4]
Me cree una cuenta nueva. Cree una donación. Me desloguié y volví a loguear.. Y nunca se envió el device_token.

**Comment by NicoBuch** [comment]
Lo raro es que hoy más temprano en un momento si lo hizo. De hecho tengo registrado el token pero después no lo hizo nunca mas. 

Como crasheaba cuando queria mandar la push, probé crear una cuenta nueva y ahí nunca más pude.

**Comment by lbadi** [comment]
Después lo reviso.

**Comment by lbadi** [comment]
Ya revise y esta registrando el token. Sin embargo hay que hacer un mejor manejo de los token dado que estoy volviendo a pedir un nuevo token cada vez que deslogeo y logro. Lo correcto seria desvincular el token con el usuario, pero guardarse ese token para vincularlo con otro usuario.
Sin embargo cierro esta issue ya que esto funciona.
